//MEMBERS
export const GET_MEMBER = "GET_MEMBER";
export const GET_MEMBERS = "GET_MEMBERS";
export const ADD_MEMBER = "ADD_MEMBER";
export const UPDATED_MEMBER = "UPDATED_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const LOADING_MEMBERS = "LOADING_MEMBERS";

//SEASONS
export const GET_SEASON = "GET_SEASON";
export const GET_SEASONS = "GET_SEASONS";
export const SEASON_REMOVE_MEMBER = "SEASON_REMOVE_MEMBER";
export const SEASON_ADD_MEMBER = "SEASON_ADD_MEMBER";

//ERRORS
export const GET_ERRORS = "GET_ERRORS";

//MISC
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const ALERT_OPEN = "ALERT_OPEN";
export const ALERT_CLOSE = "ALERT_CLOSE";
